version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:14.16.1

    steps:
      - checkout
      - run: |
          yarn install
          yarn build

      - run: |
          aws s3 sync dist s3://$AWS_S3_BUCKET_NAME/container/latest

